## Parsed the tabular format 
When the program do a multi fasta our objective is to create a distance matrix o disimilarity matrix to used as a object for clustering in order to genereta a tree of distaces, note that this metos is not for generating a filogentic tree.

In [3]:
#Import the packages  
import pandas as pd 
import numpy as np 

#read the tsv
Data_frame_raw=pd.read_csv("../results/citrocromeC_seq_hmmr_clean_aling_clean.tsv", sep="\t",names=["query", "subject","score"])

axis_matrix=list(Data_frame_raw.drop_duplicates(subset="query")["query"]) 

#we make the matrix using pivot 
Matrix_df=Data_frame_raw.pivot(
    index="query",
    columns="subject",
    values="score"
) 
Matrix_df=Matrix_df.reindex(index=axis_matrix, columns=axis_matrix)
#we make a symetric matrix 
matrix_sym = Matrix_df.copy()

columns_mtrx=list(matrix_sym.columns)

for i in matrix_sym.index:
    for j in columns_mtrx:
        if pd.notna(Matrix_df.loc[i,j]):
            matrix_sym.loc[j,i] = Matrix_df.loc[i,j]
        elif pd.notna(Matrix_df.loc[j,i]):
            matrix_sym.loc[i,j] = Matrix_df.loc[j,i] 
    columns_mtrx.remove(i)
            

for col in matrix_sym.columns: 
    #we asign the diagonal of the matrix in 0 
    matrix_sym.loc[col,col]=0 

#obtain the max value from de matrix 
max_score=matrix_sym.max().max()

matrix_sym=matrix_sym/max_score
matrix_sym=matrix_sym.fillna(0)
matrix_sym

subject,A2Y4S9,A4VND9,A4YQU0,A8HZ17,A8WQY3,A8X769,B4USV4,D3NRE7,D5ARP7,D5QVH0,...,P43302,P53698,P54820,P55496,P56205,P59218,P62772,P62773,P62894,P62895
query,,,,,,,,,,,,,,,,,,,,,
A2Y4S9,0.000000,0.021228,0.027992,0.028824,0.135276,0.127992,0.150884,0.022789,0.030073,0.099376,...,0.018835,0.147763,0.087721,0.024037,0.152966,0.142560,0.220604,0.220604,0.150884,0.150884
A4VND9,0.021228,0.000000,0.027680,0.026015,0.020812,0.000000,0.026015,0.036108,0.032466,0.019979,...,0.081790,0.000000,0.019251,0.000000,0.022060,0.000000,0.023205,0.023205,0.024037,0.024037
A4YQU0,0.027992,0.027680,0.000000,0.371488,0.026015,0.028408,0.029657,0.308012,0.268470,0.026015,...,0.035276,0.026847,0.024870,0.028408,0.032882,0.024454,0.027680,0.027680,0.029657,0.029657
A8HZ17,0.028824,0.026015,0.371488,0.000000,0.024037,0.024454,0.027263,0.297607,0.277836,0.019667,...,0.040895,0.028408,0.000000,0.030801,0.029657,0.028408,0.027263,0.027263,0.026431,0.026431
A8WQY3,0.135276,0.020812,0.026015,0.024037,0.000000,0.187305,0.137357,0.027263,0.023621,0.083351,...,0.000000,0.121748,0.093757,0.000000,0.121748,0.127992,0.137357,0.137357,0.135276,0.135276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P59218,0.142560,0.000000,0.024454,0.028408,0.127992,0.114464,0.149844,0.025286,0.026847,0.095421,...,0.019251,0.166493,0.093340,0.024870,0.174818,0.000000,0.147763,0.147763,0.150884,0.150884
P62772,0.220604,0.023205,0.027680,0.027263,0.137357,0.129032,0.149844,0.022477,0.030073,0.096150,...,0.018418,0.154006,0.088554,0.025598,0.148803,0.147763,0.000000,0.239334,0.148803,0.148803
P62773,0.220604,0.023205,0.027680,0.027263,0.137357,0.129032,0.149844,0.022477,0.030073,0.096150,...,0.018418,0.154006,0.088554,0.025598,0.148803,0.147763,0.239334,0.000000,0.148803,0.148803
P62894,0.150884,0.024037,0.029657,0.026431,0.135276,0.130073,0.212279,0.027263,0.026015,0.094173,...,0.000000,0.155047,0.086576,0.022789,0.161290,0.150884,0.148803,0.148803,0.000000,0.223725
P62895,0.150884,0.024037,0.029657,0.026431,0.135276,0.130073,0.212279,0.027263,0.026015,0.094173,...,0.000000,0.155047,0.086576,0.022789,0.161290,0.150884,0.148803,0.148803,0.223725,0.000000

In [3]:
Data_frame_raw = pd.read_csv(
    "../results/citrocromeC_seq_hmmr_clean_aling_clean.tsv",
    sep="\t",
    names=["query", "subject", "score"]
)

axis_matrix = sorted(
    set(Data_frame_raw["query"]).union(set(Data_frame_raw["subject"]))
)

Matrix_df = Data_frame_raw.pivot(
    index="query",
    columns="subject",
    values="score"
)

Matrix_df = Matrix_df.reindex(index=axis_matrix, columns=axis_matrix)

# Simetrización robusta
matrix_sym = np.maximum(Matrix_df, Matrix_df.T)

# Diagonal en 0
np.fill_diagonal(matrix_sym.values, 0)

# Normalización
max_score = np.nanmax(matrix_sym.values)
matrix_sym = matrix_sym / max_score


matrix_sym

,A2Y4S9,A4VND9,A4YQU0,A8HZ17,A8WQY3,A8X769,B4USV4,D3NRE7,D5ARP7,D5QVH0,...,P43302,P53698,P54820,P55496,P56205,P59218,P62772,P62773,P62894,P62895
A2Y4S9,0.000000,NaN,0.027992,0.028824,0.135276,0.127992,0.150884,0.022789,0.030073,0.099376,...,NaN,0.147763,0.087721,0.024037,0.152966,0.142560,0.220604,0.220604,0.150884,0.150884
A4VND9,NaN,0.000000,0.027680,0.026015,NaN,NaN,0.026015,0.036108,0.032466,0.019979,...,0.081790,NaN,0.019251,NaN,0.022060,NaN,0.023205,0.023205,0.024037,0.024037
A4YQU0,0.027992,0.027680,0.000000,0.386056,0.026015,0.028408,0.029657,0.308012,0.268470,0.026015,...,0.036108,0.026847,0.025286,0.028408,0.032882,0.024454,0.027680,0.027680,0.029657,0.029657
A8HZ17,0.028824,0.026015,0.386056,0.000000,0.024037,0.024454,0.027263,0.297607,0.277836,NaN,...,0.040895,0.028408,NaN,0.030801,0.029657,0.028408,0.027263,0.027263,0.026431,0.026431
A8WQY3,0.135276,NaN,0.026015,0.024037,0.000000,0.187305,0.137357,0.027263,0.023621,0.083351,...,NaN,0.121748,0.093757,NaN,0.121748,0.127992,0.137357,0.137357,0.135276,0.135276
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P59218,0.142560,NaN,0.024454,0.028408,0.127992,0.114464,0.149844,0.025286,0.026847,0.095421,...,0.019251,0.166493,0.093340,0.024870,0.174818,0.000000,0.147763,0.147763,0.150884,0.150884
P62772,0.220604,0.023205,0.027680,0.027263,0.137357,0.129032,0.149844,0.022477,0.030073,0.096150,...,NaN,0.154006,0.088554,0.025598,0.148803,0.147763,0.000000,0.239334,0.148803,0.148803
P62773,0.220604,0.023205,0.027680,0.027263,0.137357,0.129032,0.149844,0.022477,0.030073,0.096150,...,NaN,0.154006,0.088554,0.025598,0.148803,0.147763,0.239334,0.000000,0.148803,0.148803
P62894,0.150884,0.024037,0.029657,0.026431,0.135276,0.130073,0.212279,0.027263,0.026015,0.094173,...,NaN,0.155047,0.086576,0.022789,0.161290,0.150884,0.148803,0.148803,0.000000,0.223725
P62895,0.150884,0.024037,0.029657,0.026431,0.135276,0.130073,0.212279,0.027263,0.026015,0.094173,...,NaN,0.155047,0.086576,0.022789,0.161290,0.150884,0.148803,0.148803,0.223725,0.000000